spring:
  #mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: gengshaohua
    password: GGGsh2021
    url: jdbc:mysql://rm-bp1z0iou2n8v330c4pd.mysql.rds.aliyuncs.com/test_transcation?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  # redis
  redis:
    database: 10
    host: r-bp1ecb4764a8f294pd.redis.rds.aliyuncs.com
    port: 6379
    password: GGGsh2021
    timeout: 50000
    retryAttempts: 3
    retryInterval: 1000
    pingConnectionInterval: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: 5000ms

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

