spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ccr_admin
    password: Ccr_admin2021
    url: jdbc:mysql://10.20.210.54:3306/ccrdb?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  # redis
  redis:
    database: 10
    host: 10.20.210.55
    port: 6380
    password: Gsh180035.
    timeout: 50000
    retryAttempts: 3
    retryInterval: 1000
    pingConnectionInterval: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: 5000ms

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

